### ISSUE TITLE
Laravel model binding generates confusing documentation

### ISSUE THREAD

**Issue by fcolecumberri** [knuckleswtf/scribe#237] opened 2021-06-08 12:00 UTC
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**

I set my route:

```php
Route::get('/audio/{audio:id}/show', [AudioController::class, 'show'])->name('api.audio.show')->whereUuid('audio');
```

and my controller:

```php
/**
* @urlParam audio string required audio's id
* @responseFile status=200 scenario="On Success" responses/audio.show.200.json
*/
public function show(Request $request, \App\Models\Audio $audio){...}
```

after generating the doc, the doc says:
![imagen](https://user-images.githubusercontent.com/12193875/121179936-8ba20980-c860-11eb-89fd-78a5702cdee8.png)

This should either says `api/audio/{audio}/show` with url parameter `audio` or says `api/audio/{id}/show` with url parameter `id`.

I think `api/audio/{audio}/show` with url parameter `audio` is better.

But having saying `api/audio/{audio}/show` with url parameter `id` makes this confusing (In this case maybe not because there is only 1 parameter, but on more cases this might be confusing)

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): PHP 8.0.7
 - Framework (Laravel/Lumen): Laravel 8.45.1
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.0.1

**Comment by shalvah** [comment] 2021-06-08 12:24
Ah, this is my first time of seeing the `{audio:id}` syntax (also `whereUuid()`). I'll need to look into how that should be handled.

**Comment by fcolecumberri** [comment] 2021-06-08 14:58
Ok, removing the urlParam only makes the doc to not understand that there is a parameter.

![imagen](https://user-images.githubusercontent.com/12193875/121207536-a765d980-c879-11eb-9e71-a6e5e061b9d2.png)

↑↑↑ no URL Parameters

Btw `whereUuid()` only tells the route that if the parameter needs to be UUID otherwise it will try to cast any string to UUID and some exceptions might happen (https://github.com/laravel/framework/issues/37549) and that is not currently fixed because fixing it might hide other errors (https://github.com/laravel/framework/pull/37551).

**Comment by dvlpr91** [comment] 2021-06-16 02:03
This is a very stupid bug.

**Comment by shalvah** [comment] 2021-07-01 13:03
This should be fixed in 3.4.0. @fcolecumberri try it out and see what you get. Also, constraints like `whereUuid` are now supported, so you should be able to get a correct example out of the box. Try removing your `@urlParam` comment first and see how it goes.

**Closed by shalvah** 2021-07-01 13:03 UTC
Labels: bug

**Comment by lioneaglesolutions** [comment] 2021-07-02 05:00
@shalvah I am also facing a similar issue;
```php
    Route::prefix('providers/{provider:uuid}')->group(function () {
        Route::resource('users.addresses', UserAddressController::class)->parameters([
            'users' => 'user:uuid',
            'addresses' => 'address:uuid',
        ]);
    });
```
![image](https://user-images.githubusercontent.com/61766491/124222970-2501ca00-db46-11eb-90d8-89ebd9e377d6.png)
Every parameters should be UUID (provider is set in a group above and is correct)

**Comment by fcolecumberri** [comment] 2021-07-02 08:43
@lioneaglesolutions how is your docblock?

**Comment by lioneaglesolutions** [comment] 2021-07-02 09:01
@fcolecumberri 
```php
    /**
     * Update user address.
     *
     * @group User Addresses
     *
     * @apiResource 201 App\Http\Resources\UserResource
     * @apiResourceModel App\Models\User
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAddressRequest $request, Provider $provider, User $user, Address $address)
    {
        $this->addressService->update($address, $request->validated());

        return response(new AddressResource($address->refresh()), 201);
    }
```

**Comment by shalvah** [comment] 2021-07-02 11:25
@lioneaglesolutions Lemme get this straight. What part of your screenshot doesn't match with your expectations? What would you expect?

Because the current behaviour of Scribe *should* give:
- URL: `providers/{provider_uuid}/users/{user_uuid}/addresses/{uuid}`

Right now, it doesn't (that's a bug), but is this what you're expecting?^^^

The reason it's not meant to give `providers/{provider}/users/{user}/addresses/{address}` is because someone pointed out in the past that end-users are more familiar with `_id` type parameters (like users/{id}` rather than model parameters (users/user), and I agree.

**Comment by lioneaglesolutions** [comment] 2021-07-02 18:38
@shalvah 

I am expecting something like;
- URL: providers/{provider}/users/{user}/addresses/{uuid}

I agree that the default should be `id` as you mentioned but in the route I have specified I am expecting the `uuid` for the address - similarly there are cases where that last parameter could be `key` or `slug`

**Comment by fcolecumberri** [comment] 2021-07-03 01:02
Maybe this should be a new issue, my original issue was the _lack of consistency_, your issue is about _renaming the PK field as id_

**Comment by lioneaglesolutions** [comment] 2021-07-03 01:08
Yeah I might open a new one today.

**Comment by shalvah** [comment] 2021-07-05 21:05
@fcolecumberri you still haven't answered me though. What about your original issue? Do I consider it solved?

**Comment by shalvah** [comment] 2021-07-05 22:12
@lioneaglesolutions from v3.5.0, `providers/{provider_uuid}/users/{user_uuid}/addresses/{uuid}` is now returned in your case. This is the expected behaviour. so please open a new issue if you want to change this behaviour.

**Comment by fcolecumberri** [comment] 2021-09-22 14:43
sorry I couldn't answer I have not been able to check the changes, now it works perfect, thanks
