### ISSUE TITLE
FormRequest bodyParameters() with file upload

### ISSUE THREAD

**Issue by Duvy2** [knuckleswtf/scribe#116] opened 2020-10-17 18:30 UTC
Hi guys, I'm struggling with documenting one endpoint that shall receive a file.
Experimenting with the these: 1.9, 2.0.0.beta and 2.0.0.beta.1 package versions.
I couldn't find any relevant documentation for the file upload using the new bodyParameters.

Here I have a test validator:
```
class TestUploadValidator extends FormRequest
{
    public function rules()
    {
      return [
        'fileInput' => 'file|required',
      ];
    }

    public function bodyParameters()
    {
        return [
            "fileInput" => [
                "example" => "public/sample.mp4"
            ]
        ];
    }
}
```

Scribe finds the file, as I modify the name, it throws a file not found exception, so that I assume is correct.

But in the end, I get the following result:
`{
    "message": "The given data was invalid.",
    "errors": {
        "fileInput": [
            "The file input failed to upload."
        ]
    }
}`

So it's not included in the request.
It's a pretty small file, not exceeding any php limit, and also the endpoint is working great, just the documentation is not correct for it.

Also I tried with the annotation:
`
@bodyParam fileInput file Example:public/sample.mp4
 `
~~This case the endpoints finally gets a file, that I saved temporary to examine if it's correct, but that happens to be a 0 byte .jpeg extension dummy file.
My point is also to validate the mime types if it's a video.~~

I also get the same result.

I can't really go deeper in that investigation, could someone help how shall this be done? (preferable the bodyParameter() approach)

**Comment by shalvah** [comment] 2020-10-17 19:35
Hmm. I'll check this out. Can you dump the contents of the request in your controller?

**Comment by Duvy2** [comment] 2020-10-17 20:41
The content is an empty "[]" both ways, but the files are interesting:
With the
```
public function bodyParameters()
    {
        return [
            "fileInput" => [
                "example" => "public/sample.mp4"
            ]
        ];
    }
```
this:
```
Symfony\Component\HttpFoundation\FileBag Object
(
    [parameters:protected] => Array
        (
            [fileInput] => Illuminate\Http\UploadedFile Object
                (
                    [test:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 
                    [originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => sample.mp4
                    [mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => video/mp4
                    [error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
                    [hashName:protected] => 
                    [pathName:SplFileInfo:private] => public/sample.mp4
                    [fileName:SplFileInfo:private] => sample.mp4
                )

        )

)

```
This case, the FormRequest validator fails the check with: "The file input failed to upload".
With the
```
/*
 * @bodyParam fileInput file Example: public/sample.mp4
 */
```
this:
```
Symfony\Component\HttpFoundation\FileBag Object
(
    [parameters:protected] => Array
        (
            [fileInput] => Illuminate\Http\Testing\File Object
                (
                    [name] => test.jpg
                    [tempFile] => Resource id #1206
                    [sizeToReport] => 10240
                    [mimeTypeToReport] => 
                    [test:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 1
                    [originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => test.jpg
                    [mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => image/jpeg
                    [error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
                    [hashName:protected] => 
                    [pathName:SplFileInfo:private] => C:\Users\Duvy\AppData\Local\Temp\php3E90.tmp
                    [fileName:SplFileInfo:private] => php3E90.tmp
                )

        )

)
```
Here the FormRequest initial check passes, but when I'm including mime type check, it obviously fails for a video.

I'm testing with laravel 8, and latest scribe available with composer, Win 10, php 7.4, tried also absolute path and with "\" and "/" folder separator, the result is the same as above.
Shall I paste the whole $request?

**Comment by shalvah** [comment] 2020-10-17 20:49
I don't think the problem is the path. You can see they're different object classes. Symfony's UploadedFile, and Laravel's Testing File which extends the first. Is the second example what happens with annotations even with an example supplied? (Btw, make sure to put a space after the colon in your "Example:")

**Comment by Duvy2** [comment] 2020-10-17 21:36
@shalvah I'll keep an eye on the space, sorry for the confusion, the second example is my bad, placed the annotation to the wrong place, so it didn't have an example at all... so this way the generated test file is reasonable ^^

Now it's in the right place, and using the annotation also generates the same result as the bodyParameter() version, and fails on the same validation rule.
(I edited the previous posts not to confuse anyone)

**Comment by shalvah** [comment] 2020-10-17 21:38
Try moving the file you're uploading to somewhere else, maybe outside your app.

**Comment by Duvy2** [comment] 2020-10-18 17:39
Scribe gets the file read, and also sends it, but for a reason if if the FormRequest requires the value, it validates as it's not there.

I paste the Validator and Controller:


The TestValidator:
```
use Illuminate\Foundation\Http\FormRequest;

class TestValidator extends FormRequest
{
    public function authorize()
    {
      return true;
    }

    public function rules()
    {
      return [
        'video' => 'file|required',
      ];
    }
}
```

The Controller function that is called to verify the uploaded file:
```
/**
     * Test upload file
     * @bodyParam video file required Example: sample.mp4
     */
    public function upload(TestValidator $request)
    {
        $file = $request->video->store('temp');
        return ["success" => true];
    }
```

Even disabled all middlewares, if it matters, it's registered as a Laravel API endpoint.
For that I get the following scribe response:
```
Example response (422):

{
    "message": "The given data was invalid.",
    "errors": {
        "video": [
            "The video failed to upload."
        ]
    }
}
```

If in the FormRequest I comment out the actual validation for the "video", than I can see that the file is being sent, the response is:
```
Example response (200):

{
    "success": true
}
```
And also appears in the temp folder as it should be done in the test controller function.
From postman, Scribe generates the endpoint also works correctly, with the file added.

Shall the file upload work with a properly set up FomRequest validation?

**Comment by Duvy2** [comment] 2020-10-18 18:35
I found some infos:
When the validator checks for a valid file, in the `vendor/symfony/http-foundation/File/UploadedFile.php` the  isValid() function, returns with a false value when I'm using an example file for Scribe.

**Comment by Duvy2** [comment] 2020-10-19 18:48
I rephrase the issue:
File upload not passes FormRequest validation rule (even if only "video" => "required" is given), just tried it out with a brand new installation of Laravel 8.x and Scribe (2.0.0-beta, beta-1, and 1.9)

Unfortunately I couldn't find out why.
Shall I open a bug for this?

**Comment by shalvah** [comment] 2020-10-20 14:28
Thanks for this. I think this should be fixed in the latest v2 (no release, just the branch v2.x-dev)

**Comment by shalvah** [comment] 2020-11-14 11:58
@Duvy2 not heard from you; closing this with the assumption that it's fixed (IN https://github.com/knuckleswtf/scribe/commit/5c7e0c89df754099fe21fcf2603e026a8d320f68).

**Closed by shalvah** 2020-11-14 11:58 UTC
Labels: question
