### ISSUE TITLE
How to deal with Resources that use more attributes than the model have?

### ISSUE THREAD

**Issue by throcha-aiq** [knuckleswtf/scribe#706] opened 2023-08-14 20:50 UTC
### Scribe version

4

### Your question

I recently updated scribe to v4 and I am getting an error because of I use an attribute in the Resource that the model don't have.

this is the error:

`ⓘ Processing route: [POST] api/banner/{banner}
⚠ No bodyParameters() method found in App\Http\Requests\Banner\BannerRequest. Scribe will only be able to extract basic information from the rules() method.
⚠ Couldn't detect an Eloquent API resource model from your `@apiResource`.
Either specify a model using the `@apiResourceModel` annotation, or add an `@mixin` annotation in your resource's docblock.
✖ Failed processing route: [POST] api/banner/{banner} - Exception encountered.
✖ ErrorException in /home/thiago/projetos/painel-core/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php at line 254: Undefined array key "id"
✖ Run this again with the --verbose flag to see the full stack trace.
`

already tried to use @mixin but I got another error. Maybe I used the wrong way.
Is there a way to skip this verification?

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment] 2023-08-26 15:23
duplicate of #709

**Closed by shalvah** 2023-08-26 15:23 UTC
Labels: question, triage
