### ISSUE TITLE
scribe:generate doesn't overwrite the existing markdown files

### ISSUE THREAD

**Issue by tomcoonen** [knuckleswtf/scribe#60] opened 2020-07-24 07:35 UTC
**What happened?**
1. I set my configuration to `'type' => 'laravel',`
2. Then I ran `php artisan scribe:generate`
3. The files in the `resources/docs/groups` are not updated, removing the file and generating again creates the correct file

**My environment:**
 - PHP version: 7.4
 - Framework (Laravel/Lumen) and version: Laravel 7 latest
 - Scribe Version: 1.3.0

**Comment by shalvah** [comment] 2020-07-24 14:14
Did you modify those group files manually after generation?

**Comment by tomcoonen** [comment] 2020-07-24 18:25
No only removed them a couple of times now.

**Comment by georgimorozov** [comment] 2020-08-26 22:09
Just to chime in my vague guess on this - this was posted shortly after the release of 1.3 and might be related to a version update and cache or something.  I had a similar issue when going from 1.3 to 1.4, where I thought I was going crazy, but deleting the existing generated files made everything work normally again.

**Comment by tomcoonen** [comment] 2020-09-15 09:37
@shalvah I use the `--force` flag to update now, so that helps me since I don't modify the markdown files.

But if it is the idea to update unmodified files without this flag, than the issue is still present.

**Comment by shalvah** [comment] 2020-09-15 18:48
> what's the CLI output when you run the generate command?

This would really be helpful, because it would tell you "Skipping modified file..." if those files have been modified.

Going to close this issue because I can't reproduce. I test this functionality every time I work on Scribe, and it works fine.

Here's what you can do:
- inspect the console output to confirm that those files are showing up as being externally modified
- check the resources/docs/.filemtimes file. This file tracks the last time each file was modified by Scribe. Delete your docs, do a fresh run, and copy out the contents of this file. Wait a minute or so, do another run (don't --force it) and compare the contents of the file.
- you can also do some debugging by doing some logging of the actual file modification time in the relevant writer class. 

https://github.com/knuckleswtf/scribe/blob/091c71f6631711f405f77f702ef5317f963cc741/src/Writing/Writer.php#L448

It's possible something is external modifying those files—maybe your IDE is formatting them, changing line endings or adding a blank line

**Closed by shalvah** 2020-09-15 18:48 UTC
Labels: bug
