### ISSUE TITLE
Generating documentation doesn't respect config directory for assets listed in index.html

### ISSUE THREAD

**Issue by zachisit** [knuckleswtf/scribe#78] opened 2020-08-25 18:42 UTC
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. I set my configuration to...
`'output_path' => 'public/docs',`
2. Then I ran `php artisan scribe:generate` ...
3. But I saw...
Each time the `index.html` is generated, it doesn't include the `'/docs` directory reference for the css and js files listed in the `head` of the file. So each time I generate, I have to add this directory for the assets to load.

instead of...
Realizing the directory path set in the `config/scribe.php` file and adding it for me.

**Screenshots and stack traces:**

**My environment:**
 - PHP version: 
7.4
 - Framework (Laravel/Lumen) and version: 
 Lumen (7.2.1) 
 - Scribe Version: 
1.4

**My Scribe config (minus the comments):**
```
<?php

return [
    'type' => 'static',

    'static' => [
        'output_path' => 'public/docs',
    ],

    'laravel' => [
        'add_routes' => true,

        'docs_url' => '/docs',

        'middleware' => [],
    ],

    'auth' => [
        'enabled' => false,

        'in' => 'bearer',

        'name' => 'token',

        'use_value' => env('SCRIBE_AUTH_KEY'),

        'extra_info' => 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.',
    ],

    'intro_text' => <<<INTRO

<aside>As you scroll, you'll see code examples for working with the API in different programming languages in the dark area to the right (or as part of the content on mobile), and you can switch the programming language of the examples with the tabs in the top right (or from the nav menu at the top left on mobile).</aside>
INTRO
    ,

    
    'example_languages' => [
        'bash',
        'javascript',
    ],

    'base_url' => null,

   
    'title' => null,

    'description' => 'Description chang eme later',

   
    'postman' => [
        'enabled' => false,


        'base_url' => null,

        'description' => null,


        'auth' => null,


        'overrides' => [
            // 'info.version' => '2.0.0',
        ],
    ],

    
    'openapi' => [
        'enabled' => true,

        
        'overrides' => [
            // 'info.version' => '2.0.0',
        ],
    ],

    'default_group' => 'Endpoints',

   
    'logo' => false,

  
    'router' => 'laravel',

    
    'routes' => [
        [
            'match' => [
                'domains' => ['*'],

                 'prefixes' => ['*'],

                'versions' => ['v1'],
            ],

            'include' => [
                // 'users.index', 'healthcheck*'
            ],

            'exclude' => [
                // '/health', 'admin.*'
            ],

            'apply' => [
                'headers' => [
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json',
                ],

                'response_calls' => [
                    'methods' => ['GET'],

                    'config' => [
                        'app.env' => 'documentation',
                        // 'app.debug' => false,
                    ],

                    'cookies' => [
                        // 'name' => 'value'
                    ],

                    'queryParams' => [
                        // 'key' => 'value',
                    ],
                    'bodyParams' => [
                        // 'key' => 'value',
                    ],

                    'fileParams' => [
                        // 'key' => '/home/me/image.png',
                    ],
                ],
            ],
        ],
    ],

    'fractal' => [
        'serializer' => null,
    ],

    'faker_seed' => null,

    'strategies' => [
        'metadata' => [
            \Knuckles\Scribe\Extracting\Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            \Knuckles\Scribe\Extracting\Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            \Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromQueryParamTag::class,
        ],
        'headers' => [
            \Knuckles\Scribe\Extracting\Strategies\Headers\GetFromRouteRules::class,
            \Knuckles\Scribe\Extracting\Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest::class,
            \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses' => [
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseTransformerTags::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseResponseTag::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseResponseFileTag::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\UseApiResourceTags::class,
            \Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls::class,
        ],
        'responseFields' => [
            \Knuckles\Scribe\Extracting\Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],

    'routeMatcher' => \Knuckles\Scribe\Matching\RouteMatcher::class,
    'continue_without_database_transactions' => [],
];

```

**Comment by shalvah** [comment] 2020-08-25 20:03
What path does it use?

(Also, challenge: send in a fix.😄 It sounds like it should be something not too hard to track down.)

**Comment by georgimorozov** [comment] 2020-08-26 17:59
Correct me if I am wrong but this doesn't seem like an issue with the generator. This (if it was an issue) would be an issue with Pastel. Also, I am not sure how this would happen as Pastel uses paths relative to index.html, I tried using different folders for 'public/docs' and they work fine. The output_path realistically should have no bearing on the assets other than the absolute path to index.html.

![Screen Shot 2020-08-26 at 1 58 37 PM](https://user-images.githubusercontent.com/23214770/91339277-3f3f7e80-e7a4-11ea-908d-5bdf685e72fd.png)

**Comment by shalvah** [comment] 2020-08-26 23:14
Theoretically, yes. But we still need to know from the OP what path is being used. I suspect this is a fluke from his setup, as his config looks pretty much like the default, which works alright.

**Comment by shalvah** [comment] 2020-08-26 23:15
Theoretically, yes. But we still need to know from the OP what path is being used. I suspect this is a fluke from his setup, as his config looks pretty much like the default, which works alright.

**Comment by shalvah** [comment] 2020-09-03 20:07
@zachisit

**Comment by shalvah** [comment] 2020-09-03 20:07
@zachisit ^^^

**Comment by shalvah** [comment] 2020-10-19 12:39
Hey @zachisit not heard anything from you. Going ahead to close this issue. If there's still a problem, let me know.

**Closed by shalvah** 2020-10-19 12:39 UTC
Labels: bug

**Comment by blake-ascent** [comment] 2021-05-20 18:33
@zachisit I am also having this same issue where css and js files are not being included after running scribe generate. Did you have a workaround for this?

**Comment by zachisit** [comment] 2021-05-20 18:50
@blake-ascent Unfortunately there is no such work around. I had to write a separate Readme around this very concept, providing the update html that would be needed after a compilation. Pretty gross. Apparently the authors of this package assumes you'll build once and never have to do again?

**Comment by shalvah** [comment] 2021-05-20 19:06
No, the authors of this package (which don't have an obligation to you) did try to help you almost a year ago, but you ignored their requests for clarification and choose to blame them instead, so...yay you.👏

**Comment by zachisit** [comment] 2021-05-20 19:16
@shalvah Now my feelings are hurt

**Comment by blake-ascent** [comment] 2021-05-20 19:43
@shalvah my configs are similar to zachs, but I am using the 'laravel' type, and I am getting the unformatted html page when /docs redirects me to the the blade.php file.

**Comment by shalvah** [comment] 2021-05-21 12:23
Yeah, so the question I'm asking is what's the path to the CSS file that your browser is trying to load?

**Comment by blake-ascent** [comment] 2021-05-21 15:45
From the repo root, the CSS files that the blade file is referring to are located in public/docs/css/{css files}.
It seems like when I run scribe generate, with the laravel type selected, my {project URL}/docs endpoint is actually going to the public/docs/index.html file instead of the blade file.

**Comment by blake-ascent** [comment] 2021-05-21 15:51
Oh sorry, ignore that last comment, I had an issue with my project. scribe generate does point me to the index.blade.php file, but for example, the {{ asset("vendor/scribe/css/style.css") }}  fails to find the file.

**Comment by shalvah** [comment] 2021-05-24 10:57
C'mon, just answer the question 😭: **What's the link that your browser tries to load for the CSS files?** Look at Dev Tools and see the path to the CSS files that your browser tries to fetch.

Also, have you tried running again with `--force`?

What you're saying should have been covered by the `performFinalTasksForLaravelType()` method.

https://github.com/knuckleswtf/scribe/blob/9a067a1dbe8293a9b162eb0fd2edcb70cf44b0a4/src/Writing/Writer.php#L274

I suspect you ran into some edge case. Did you generate `static` docs first, before switching to `laravel`?Try [removing those CSS files](https://scribe.readthedocs.io/en/latest/troubleshooting.html#clear-previously-generated-docs) and generating again.

**Comment by blake-ascent** [comment] 2021-05-24 14:48
Oh I think I see! The path is https://localhost:8000/vendor/scribe/css/style.css, but I only am running http locally (not https).
If I go to http://localhost:8000/vendor/scribe/css/style.css in my browser, it does retrieve the file.

**Comment by shalvah** [comment] 2021-05-24 14:51
That's weird. That means either Laravel is generating HTTPS URLs for you, or your browser is redirecting to HTTPS. Doesn't seem to be from Scribe.

**Comment by shalvah** [comment] 2021-05-30 11:53
I just realised the cause of the original issue. The `static` type does not work correctly if your Laravel app is running. This is changing in v3.

**Comment by shalvah** [comment] 2021-05-30 12:03
(which is coming in two weeks). Not sure, but this _may_ fix your issue @blake-ascent .

**Comment by blake-ascent** [comment] 2021-06-02 15:51
Ok, I'll update then and try it out. Thanks @shalvah

**Comment by alijawadi** [comment] 2022-05-16 19:48
I'm using v3 and still have the issue!
![image](https://user-images.githubusercontent.com/32621518/168670773-bbb8d482-df8c-413f-baa7-319087a0aa1f.png)

**Comment by shalvah** [comment] 2022-05-18 20:59
Can you open another issue with details of what exactly you're encountering?

**Comment by Jrius4** [comment] 2023-07-25 11:27
Thanks Scribe team for the great lib, I faced a similar problem this is how I resolved it :-> I updated my configuration as 'assets_directory' =>"storage/public/scribe", and  base_url=>"www.example.com" not as "www.example.com/" with laravel. and all was well.
