### ISSUE TITLE
Strange "0" key in example payload on the right side

### ISSUE THREAD

**Issue by ziming** [knuckleswtf/scribe#573] opened 2022-11-29 07:45 UTC
After a recent composer update the example payload on the right side start showing things like

        "0": "ullam",

examples

Example 1: PHP
```php
'dsfdsfds' => 'qweqweqwe',
            'qweqweq' => '4602ea4b-c112-38a0-82a2-ed68a84cc29b',
            'qweqweq' => 'e4b04d87-a8fd-3ef3-af47-92f4b400456d',
            'asdas_asdasd' => [
                'ullam', // <-- weird? not in my FormRequest
                'Abc' => 'P',
                'Def' => 25,
                'Ghds' => 'qweqweqweqw',
                'asdas' => 'qwewqeqwe',
                'asdas' => 'I am rich!',
                'asd' => 4,
                'asds' => 'qwe qweq',
                'asd' => 'qeqweqweqeq',
            ],
```

Example 2: Python

```python
payload = {
    "qwewq": "wqeqwqwe",
    "qweqw": "4602ea4b-c112-38a0-82a2-ed68a84cc29b",
    "asdasdsaa": "e4b04d87-a8fd-3ef3-af47-92f4b400456d",
    "eqwedqweqweq": {
        "0": "ullam", #Again Here weird
        "qweqw": "P",
        "asdqwqw": 25,
        "adsasd": "asdsa",
        "hgfhfghfhgfhfg": "iwbribzdamn",
        "qweqw": "I am rich!",
        "qweqw": 4,
        "qweqw": "qwe qwe",
        "aqwewqsd": "qweqweqw"
    }
}
```

My Form Request has no "0" key at all and it didn't appear before the composer update

**Comment by shalvah** [comment] 2022-11-29 09:24
Hmm, will check. Does this happen on endpoints that don't use FormRequests?

**Comment by ziming** [comment] 2022-12-01 13:55
hmm all my endpoints use form requests. so I dont know

**Comment by shalvah** [comment] 2022-12-01 18:29
You need to give me an example of the FormRequest data that produces this, and information about your  setup and environment.

Please, whenever reporting an issue, do not just say "X is wrong". Provide enough information for me to replicate X. Otherwise **I will close the issue**. I can't magically know what exact things are going on that made something happen.Sometimes what you're reporting is even already fixed in a later version.

This is why the `bug` template exists; I'm not sure why you completely disregarded it. That's not very respectful of my time. I'm not your paid tech support; the least you can do is provide enough info so we can work together and figure this out.

**Comment by ziming** [comment] 2022-12-02 03:13
I was planning to make a version without form request to test if it work without form request and answer this thread again on friday and woke up to this today.

apologies that u felt this way. I thought it was alright since for my own open source packages I'm fine with people just opening an issue with a few basic details and I probe further with new questions to investigate further. Understand u have a different style.

Have a good day

**Comment by ziming** [comment] 2022-12-02 05:55
It's friday now, haven't heard from you if you still want to hear from me, but result is nope, moving the validation from form request to within the controller ($request->validate([...]) does not solve the issue, the payload example on the right side still show the "0" key.

That' all

**Comment by shalvah** [comment] 2022-12-02 10:32
> But I don't think there is a need to jump straight to going on a rant

I went into a rant because people keep doing this. I've dealt with this several times in the past week—people open issues and don't drop enough information, and I spend time trying to investigate it, only to discover I've already fixed it in a newer version. WTF. Of course it makes me angry. I'm at a very busy time in my life; why should I be happy my time is being wasted?

You can't tell me to _not_ be angry; I created an issue template so I can get all the information I need straight up. _You_ opened and issue and ignored the whole thing, making us have to go through this back and forth.

> It's friday now, haven't heard from you

What the fuck, dude. Chill. Do I not get to sleep and do other things again? What the fuck.

**Comment by shalvah** [comment] 2022-12-02 10:32
As for your bug, you aren't still providing enough information. It's possible that it's due to one of your rules

**Comment by ziming** [comment] 2022-12-02 10:36
I think there is some misunderstandings, when I said

> It's friday now, haven't heard from you if you still want to hear from me

I mean, I'm not sure if you want to hear from me again since you seem unhappy earlier, then I proceed to go ahead to post my new findings, hoping ur not mad at me for posting when you have not replied if ur okay with me posting again or not

I'm meant to be polite but perhaps my english is not as good. Sigh

**Comment by shalvah** [comment] 2022-12-02 10:38
I see. That was a miscommunication. Anyway, there's nothing to lose in posting more information. You don't need to hear back from me for that.

**Comment by shalvah** [comment] 2022-12-02 10:39
> then followed up with a detailed repro or PR weeks/months later when I'm more free & those maintainers didn't have an issue with it. We just contribute/continue with more details or a PR fix whenever we are free. At no point did I demand a fix immediately

This is good, but, like I said, there was an issue template. I don't ask for repros, because I know it can be complex. Just give me enough information to reproduce it myself. So it's not fair when people just come up and delete all that and don't give me the information.

**Comment by shalvah** [comment] 2022-12-02 10:42
This issue is definitely caused by the order of your parameters or some specific rules. I can't help you until you give me more realistic data. The example you gave me does not help in any way.

**Comment by ziming** [comment] 2022-12-02 11:30
Moving on, My rules arrays with the rules in it

```php
[
            'a' => [
                'required', 'string', 'min:9', 'max:10',
                Rule::exists('table_a', 'id')->where(function (Builder $query) {
                    return $query->where('is_enabled', true);
                }),
            ],

            'b' => ['required', 'string', 'uuid'],
            'c' => ['required', 'string', 'uuid'],


            'd' => ['required', 'array'],

            'd.a' => ['required', 'string', 'in:P'],

            'd.b' => ['required', 'integer', 'min:1', 'max:10000'],
            'd.c' => ['required', 'string', 'size:4', 'alpha', 'uppercase'],
            'd.d' => [
                'required',
                'string',
                'max:19',
                'unique:table_b,d'
            ],
            'd.e' => [
                'nullable',
                'string',
            ],
            'd.f' => ['required', 'string', 'numeric', 'regex:/^\d+$/', 'max:15'],
            'd.g' => [
                'required',
                'string',
            ],
            'd.h' => ['required', 'string', 'max:15', 'uppercase'],
        ];
```

**Comment by shalvah** [comment] 2022-12-02 17:42
Have you tried updating to the latest (4.7.1)? That's mentioned as the first step in the troubleshooting guide.

**Comment by ziming** [comment] 2022-12-02 17:44
In my 1st comment I already said I did a composer update. so yes I am at 4.7.1 (released 4 days ago)

**Comment by shalvah** [comment] 2022-12-02 17:44
Ah, okay. I've been able to reproduce this now. 👍

**Comment by shalvah** [comment] 2022-12-02 18:15
Fixed in 4.8.0.

Let's do better in the future.

**Closed by shalvah** 2022-12-02 18:15 UTC
Labels: bug

**Comment by shalvah** [comment] 2022-12-03 17:29
For the record, I have no problem with you. My problem is with when I try to put procedures in place to make it easier to help people (the issue template) and people just ignore it and still expect help. You might feel I was unfairly harsh with you, but I'd just had several days of this, so I had no patience for another.

That aside, you've been very helpful, so thank you. I just wish you had provided the details up front (which the issue template guides you to do) and saved us this time.

**Comment by ziming** [comment] 2022-12-13 18:44
I just read your comment today as I have a lot of anxiety over the past days stopping me from clicking the notification on this issue.

Noted your preferences. Actually I don't even remember there being a template when i 1st created the issue, i have to try again to see it. My guess is my instinct just alt A + backspace right away back then. Apologies

Thanks and good luck

**Comment by shalvah** [comment] 2022-12-13 18:52
> I have a lot of anxiety over the past days stopping me from clicking the notification on this issue.

Ah, sorry about that. I know what that's like.
