### ISSUE TITLE
No-example in Form Requests

### ISSUE THREAD

**Issue by N1ebieski** [knuckleswtf/scribe#448] opened 2022-03-12 20:01 UTC
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

No-example tag in docblock parameters works very well, but how to set exactly same tag in FR's bodyParameters() method?

if I don't define example key and value in array then Scribe inserts a random value.

If I set example value as blank, null, empty string or empty array then Scribe generates these values in Postman body:

`{
    "title": "",
    "tags": [],
    "categories": [],
    "content_html": "",
    "notes": ""
}`

**Comment by shalvah** [comment] 2022-03-12 20:04
Did you try to add it at the end of the `description` in `bodyParameters()`?

**Comment by N1ebieski** [comment] 2022-03-12 20:11
If you mean something like this:

`
            'content_html' => [
                'description' => 'Description. No-example'
            ],
`

it doesn't work. Scribe inserts random value.

**Comment by leandrodiogenes** [comment] 2022-03-12 20:32
Hi @N1ebieski, Try something like that.
```php
'content_html' => [ 'description' => 'Description', 'example'=>'My example' ]
```

**Comment by N1ebieski** [comment] 2022-03-12 20:37
@leandrodiogenes Hmm but I want no example...

**Comment by leandrodiogenes** [comment] 2022-03-12 20:37
Try with an empty value on 'example' key

**Comment by N1ebieski** [comment] 2022-03-12 20:39
@leandrodiogenes then yes, input value is empty on the docs website but in Postman body I have:

`{ "content_html": "" }`

No-example tag is not the same as an empty string value.

**Comment by leandrodiogenes** [comment] 2022-03-12 20:41
what kind of value you want on postman body?

**Comment by N1ebieski** [comment] 2022-03-12 20:42
I don't want a value for this parameter at all :)

**Comment by shalvah** [comment] 2022-03-12 21:22
Oh, the issue is solely in the Postman collection? The docs page works fine? Seems like regards a bug that could be fixed...PRs welcome.

**Comment by leandrodiogenes** [comment] 2022-03-12 21:24
I have an solution to your problem. Indeed i cant do what you want. But with an custom Strategies you can.

Create an custom GetFromFormRequest strategy.
```php

namespace App\Docs\Strategies\BodyParameters;

use ReflectionFunctionAbstract;

class GetFromFormRequest extends \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest {

    public function getParametersFromFormRequest(ReflectionFunctionAbstract $method, $route = null): array {
        return array_filter(parent::getParametersFromFormRequest($method, $route), function($parameter) {
            return $parameter['example'] !== 'No-example';
        });
    }

}
```

Remember to replace the default strategy in scribe config file to process your new strategy
```php
'bodyParameters'  => [
    Strategies\BodyParameters\GetFromLaravelAction::class,
    //Strategies\BodyParameters\GetFromFormRequest::class,
    \App\Docs\Strategies\BodyParameters\GetFromFormRequest::class,//HERE ARE YOUR NEW STRATEGY
    Strategies\BodyParameters\GetFromInlineValidator::class,
    Strategies\BodyParameters\GetFromBodyParamTag::class,
]
```

So, now you just need to add an example with value 'No-example' on parameters of your formRequest
```php

class TesteRequest extends FormRequest {
    public function rules(): array {
        return [
            'test' => ['string', 'max:255'],
        ];
    }

    function bodyParameters() {
        return [
            'test' => [
                'example' => 'No-example',
            ],
        ];
    }
}

```

**Comment by leandrodiogenes** [comment] 2022-03-12 21:29
There is an issue on the strategy here is the new one.
```php

use ReflectionFunctionAbstract;

class GetFromFormRequest extends \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest {

    public function getParametersFromFormRequest(ReflectionFunctionAbstract $method, $route = null): array {
        return array_map(function($parameter) {
            $parameter['example'] = $parameter['example'] === 'No-example' ? null : $parameter['example'];
            return $parameter;
        }, parent::getParametersFromFormRequest($method, $route));
    }

}
```

**Comment by shalvah** [comment] 2022-03-12 23:05
Nice... Can you PR this fix to the repo?

**Comment by maksymcherevko** [comment] 2022-08-16 16:45
Are there any plans to fix this bug in the repository soon? Thanks.

**Comment by shalvah** [comment] 2022-12-02 18:03
I believe this was fixed by https://github.com/knuckleswtf/scribe/pull/511, not sure why it's still open.

**Closed by shalvah** 2022-12-02 18:03 UTC
Labels: question
